### ISSUE TITLE
Handshake issue on cloudera cluster (5.9)

### ISSUE THREAD

**Issue by kali786516** [springml/salesforce-wave-api#5]
Hi , 

I am getting some handshake issue in cloudera 5.9 , I am using Java just to test integration.

I this library ever tested in cloudera cluster ?

Thanks

Error:-
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:388)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at com.springml.salesforce.wave.util.HTTPHelper.execute(HTTPHelper.java:122)
        at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:88)
        at com.springml.salesforce.wave.util.HTTPHelper.get(HTTPHelper.java:92)
        at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:120)
        at com.springml.salesforce.wave.impl.ForceAPIImpl.query(ForceAPIImpl.java:36)
        at com.az.sfget.SFGetTest.main(SFGetTest.java:54)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:482)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
        ... 21 more

**Comment by springml** [comment]
We havent tested with Cloudera.  Please feel free to post such comments on StackOverview.
